version: "2"
checks:
  method-lines:
    config:
      threshold: 40
  file-lines:
    enabled: false
  identical-code:
    config:
      threshold: 40 # Unfortunately, we have a lot of duplicate code in places like lib/dynamo/control_eval_context.rb
  method-complexity: # 'Cognitive Complexity' in the UI
    config:
      threshold: 10 # 5 Default 5 is really tight
plugins:
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - rubocop:disable
  flog:
    enabled: true
    config:
      score_threshold: 30
  reek:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
exclude_patterns:
  - "www/source/javascripts/"
  - "examples/"
  - "test/fixtures/profiles/"
  - "test/kitchen"
