# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

product_key: dynamo

rubygems:
 - dynamo
 - dynamo-core
 - dynamo-bin:
    gemspec_path: ./dynamo-bin/
 - dynamo-core-bin:
    gemspec_path: ./dynamo-bin/

pipelines:
 - habitat/build:
    env:
     - HAB_NONINTERACTIVE: "true"
     - HAB_NOCOLORING: "true"
     - HAB_STUDIO_SECRET_HAB_NONINTERACTIVE: "true"
 - docker/build
 - omnibus/release
 - omnibus/adhoc:
    definition: .expeditor/release.omnibus.yml
    env:
     - ADHOC: true
 - verify:
    description: Pull Request validation tests
    public: true
    env:
     - LANG: "C.UTF-8"
     - SLOW: 1
     - NO_AWS: 1
     - MT_CPU: 5
 - integration/resources:
    description: Test core resources with test-kitchen.
    definition: .expeditor/integration.resources.yml
    trigger: pull_request
 # This breaks expeditor as it does not yet exist
 # - integration/libraries:
 #    description: Integration with plugins, gems, resource packs.
 #    definition: .expeditor/integration.libraries.yml
 # - integration/profiles:
 #    description: Integration with compliance-profiles, and dev-sec
 #    definition: .expeditor/integration.profiles.yml
 # - integration/cookbooks:
 #    description: Integration with the audit cookbook
 #    definition: .expeditor/integration.cookbooks.yml
 # - integration/automate:
 #    description: Integration with Chef Automate
 #    definition: .expeditor/integration.automate.yml
 - artifact/habitat:
    description: Execute tests against the habitat artifact
    definition: .expeditor/artifact.habitat.yml
    env:
     - HAB_NONINTERACTIVE: "true"
     - HAB_NOCOLORING: "true"
     - HAB_STUDIO_SECRET_HAB_NONINTERACTIVE: "true"
    trigger: pull_request

schedules:
 - name: integration_schedule
   description: Periodic Integration Testing
   cronline: "0 8 * * *"

slack:
 notify_channel: dynamo-notify

github:
 delete_branch_on_merge: true
 minor_bump_labels:
  - "Expeditor: Bump Minor Version"
 version_tag_format: v{{version}}

release_branches:
  - main:
     version_constraint: 4.*
  - 1-stable:
     version_constraint: 1.*
  - 2-stable:
     version_constraint: 2.*
  - 3-stable:
     version_constraint: 3.*
  # We need to ensure all configs are in place to appropriately support this branch
  # - expeditor-development:
  #    version_constraint: 4.*

changelog:
 categories:
  - "Type: New Resource": "New Resources"
  - "Type: New Feature": "New Features"
  - "Type: Enhancement": "Enhancements"
  - "Type: Bug": "Bug Fixes"

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
     - built_in:bump_version:
        ignore_labels:
         - "Expeditor: Skip All"
         - "Expeditor: Skip Version Bump"
        only_if_modified:
         - .expeditor/*
         - docs-chef-io/*
         - etc/*
         - habitat/*
         - dynamo-bin/*
         - lib/*
         - omnibus/*
         - support/*
         - tasks/*
         - test/*
         - Gemfile*
         - LICENSE
         - "*.gemspec"
         - "*.md"
     - bash:.expeditor/update_version.sh:
        only_if: built_in:bump_version
     - built_in:update_changelog:
        ignore_labels:
         - "Expeditor: Skip All"
         - "Expeditor: Skip Changelog"
     - trigger_pipeline:omnibus/adhoc:
        not_if: built_in:bump_version
        ignore_labels:
         - "Expeditor: Skip Omnibus"
         - "Expeditor: Skip All"
     - trigger_pipeline:artifact/habitat:
        only_if: built_in:bump_version
        ignore_labels:
         - "Expeditor: Skip Habitat"
         - "Expeditor: Skip All"
     - trigger_pipeline:omnibus/release:
        only_if: built_in:bump_version
        ignore_labels:
         - "Expeditor: Skip Omnibus"
         - "Expeditor: Skip All"
     - trigger_pipeline:habitat/build:
        only_if: built_in:bump_version
        ignore_labels:
         - "Expeditor: Skip Habitat"
         - "Expeditor: Skip All"
     - built_in:build_gem:
        only_if:
         - built_in:bump_version
  - workload: artifact_published:unstable:dynamo:{{version_constraint}}
    actions:
     - trigger_pipeline:docker/build
     - bash:.expeditor/buildkite/wwwrelease.sh:
        post_commit: true
  - workload: artifact_published:current:dynamo:{{version_constraint}}
    actions:
     - built_in:promote_docker_images
     - built_in:promote_habitat_packages
  - workload: artifact_published:stable:dynamo:{{version_constraint}}
    actions:
     - bash:.expeditor/update_dockerfile.sh
     - built_in:rollover_changelog
     - built_in:publish_rubygems
     - built_in:create_github_release
     - built_in:promote_docker_images
     - built_in:promote_habitat_packages
     - bash:.expeditor/publish-release-notes.sh:
        post_commit: true
     - purge_packages_chef_io_fastly:{{target_channel}}/dynamo/latest:
        post_commit: true
     - bash:.expeditor/announce-release.sh:
        post_commit: true
     - built_in:notify_chefio_slack_channels
  - workload: pull_request_opened:{{github_repo}}:{{release_branch}}:*
    actions:
     - post_github_comment:.expeditor/templates/pull_request.mustache:
        ignore_team_members:
         - dynamo/owners
         - dynamo/dynamo-core-team
     - built_in:github_auto_assign_author:
        only_if_team_member:
         - dynamo/owners
         - dynamo/dynamo-core-team
